### ISSUE TITLE
TikToks are not downloading, just returning error. 

### ISSUE THREAD

**Issue by SteadyStatus21** [0x464e/tiktok_to_discord#4]
Hello again!
I found another issue, and I am not sure if it is something I did, or if the bot just doesn't like me haha. 

![image](https://user-images.githubusercontent.com/73841304/193413501-e58d20d0-667c-47ec-af16-891eb188e86c.png)

Thank you so much 0x464e!
-SteadyStatus21

**Comment by 0x464e** [comment]
Yeah, awkwardly enough the implementation worked for a year in a row, but right as you found this it broke, haha.  
I'm assuming something small changed in the website I'm scraping from. Probably an easy fix, but I don't have time to fix it right this moment, very busy with school work. If you're knowledgeable with coding like this, the issue might be as simple as fixing the selector on this row:  
https://github.com/0x464e/tiktok_to_discord/blob/73bb0db8ff201116275c1fce2afa1b64034141a5/index.js#L107
If not, I'm sorry and I'll fix it as soon as I have time.

**Comment by SteadyStatus21** [comment]
Thank you for your response, and I am not very good with this kind of coding. I understand that you are in school, and I am more than happy to wait for you to have a gap in time to work on it. There is no pressure here, and I don't want there to be any. 

Again, thank you for responding so quickly, and I appreciate your work!
-SteadyStatus21

**Comment by 0x464e** [comment]
@SteadyStatus21 Hi, I pushed a fix for this since it was indeed just a small change.
I'm also planning on doing a bigger update in somewhat near future (when I have time).  
This would add support for photos TikToks as well (as of now, photos TikToks only download the audio (and they show up as mp4 as well, but they're actually just the audio track))

**Comment by SteadyStatus21** [comment]
That is truly amazing! Thank you so much @0x464e!

-SteadyStatus21

**Comment by 0x464e** [comment]
@SteadyStatus21 Hi, not sure if you're still using this, but if you are, you might have noticed how it suddenly stopped embedding some TikToks for no reason.

I've changed up the downloader so that's fixed and now there's support for photo TikToks as well.  
I just now made this change though, so I'll have to see how reliable this new downloader is, but after few minutes of testing it seems good.

Note that the new stuff is now in the master branch.

**Comment by PortalRex** [comment]
It seems this problem has returned? I am constantly getting the same error msg.

**Comment by 0x464e** [comment]
> It seems this problem has returned? I am constantly getting the same error msg.

Uh yes, seems the website I was scraping for TikTok downloads started being problematic. Third time this happens, so for now I've given up with scraping websites and I switched to [yt-dlp](https://github.com/yt-dlp/yt-dlp). (See my latest commit to master and updated instructions in README)  
All puppeteer shenanigans are also now gone, and I hope that yt-dlp should be much more reliable. The downside here is that photos TikToks are now once again not supported :c  
Maybe one day I'll have time to try for a proper implementation where photos TikToks would also be supported.

**Comment by PortalRex** [comment]
Thanks for the quick fix. Shame about the photos. At least it works lol.
