### ISSUE TITLE
Requested format is not available

### ISSUE THREAD

**Issue by caleyz** [0x464e/tiktok_to_discord#7]
On some tiktoks, namely https://vm.tiktok.com/ZGJbbRe2J/  , the code will fail because apparently the feed api endpoint isn't available for some videos.
 If running the yt-dlp exe command manually, it actually succeeds by falling back to the default webpage extraction, however I think the wrapper used in this project sees the WARNING generated and never waits for the video to be returned

C:\Users\Zack\source\repos\TikTokEmbed>yt-dlp.exe -vU https://vm.tiktok.com/ZGJbbRe2J/ --restrict-filenames -o "%(title).100B [%(id)s].%(ext)s"

[debug] Command-line config: ['-vU', 'https://vm.tiktok.com/ZGJbbRe2J/', '--restrict-filenames', '-o', '%(title).100B [%(id)s].%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.01.182131 [db9743894] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1860 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.01.182131, Current version: nightly@2023.08.01.182131
Current Build Hash: 79c94397fd3d96e036b0e748f6d580c3cbc405b819fce9f63b38a8e28844f438
yt-dlp is up to date (nightly@2023.08.01.182131)
[vm.tiktok] Extracting URL: https://vm.tiktok.com/ZGJbbRe2J/
[vm.tiktok] ZGJbbRe2J: Downloading webpage
[TikTok] Extracting URL: https://www.tiktok.com/@thecaptaincy/video/7230508097012321562?_t=8eVFG4SNKBU&_r=1
[TikTok] 7230508097012321562: Downloading video feed
**WARNING: [TikTok] 7230508097012321562: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage**
[TikTok] 7230508097012321562: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 7230508097012321562: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://v16-webapp-prime.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0037-aiso/o8WVztCbEhXPEWGHAQkQfBPYIZRfA725RDzCjC/?a=1988&ch=0&cr=0&dr=0&lr=tiktok_m&cd=0%7C0%7C1%7C0&cv=1&br=2832&bt=1416&cs=0&ds=3&ft=_RwJrBNXq8ZmoC5m_c_vjZrFLAhLrus&mime_type=video_mp4&qs=0&rc=Nzk5NmQ6aTtlOGc4PDdmN0BpajppNjU6Zmd4azMzZjczM0BeYjIzMTAtXjYxLjVhXmJiYSNwYHAtcjRval9gLS1kMWNzcw%3D%3D&btag=e00088000&expire=1691034229&l=202308022143310724B9AF8F1B008EC127&ply_type=2&policy=2&signature=2f3ed7fcf97ce418c32519c3b70a2b49&tk=tt_chain_token"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Bro_only_just_landed_in_NYC_fup_foryou_funny_npc_funnyclip_meme_lowqualitymemes_trend [7230508097012321562].mp4
[download] 100% of    2.93MiB in 00:00:00 at 5.44MiB/s

**Comment by 0x464e** [comment]
I'm unable to download or open that TikTok at all. I just get an error that it isn't available on in my Region.  
Never even knew TikTok has region locked videos, lol? What error do you get when you try to open it, if any?

But it seems like (I'm guessing) the problem you're running into here, is that the script it trying to download the format `best[vcodec=h264]`, but that format doesn't seem to be isn't available for that TikTok (try to run `yt-dlp -F https://vm.tiktok.com/ZGJbbRe2J/` and let me know what the output is)

The reason I'm downloading the best h264 format, is because the actual best format (which would be selected by default) is in h265, but Discord doesn't support h265. So I have to explicitly specify that the best h264 format is downloaded.

If this project will still use yt-dlp (as opposed to just the TikTok API) after the complete rewrite I'm planning, I might have to see if I can make the format selection a bit smarter somehow (e.g. first try best h264, then try for webm, or maybe use best non-h265 format, or something like that. Whatever is doable with yt-dlp)

**Comment by caleyz** [comment]
> Never even knew TikTok has region locked videos, lol? 

Neither did I, lol.


I can view the video completely fine in the UK.

C:\Users\Zack\source\repos\TikTokEmbed>yt-dlp -F https://vm.tiktok.com/ZGJbbRe2J/

[vm.tiktok] Extracting URL: https://vm.tiktok.com/ZGJbbRe2J/
[vm.tiktok] ZGJbbRe2J: Downloading webpage
[TikTok] Extracting URL: https://www.tiktok.com/@thecaptaincy/video/7230508097012321562?_t=8eVFG4SNKBU&_r=1
[TikTok] 7230508097012321562: Downloading video feed
WARNING: [TikTok] 7230508097012321562: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7230508097012321562: Downloading webpage
[info] Available formats for 7230508097012321562:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 576x1024   │ https │ unknown unknown

**Comment by 0x464e** [comment]
`unknown` video codec, so I guess  `best[vcodec=h264]` doesn't fall under that. So the issue seems to be what I expected.  
I guess you can also try locally to run `yt-dlp -f "best[vcodec=h264]" https://vm.tiktok.com/ZGJbbRe2J/` to replicate the issue.

Also, I just consulted the yt-dlp documentation, and it's apparently possible to do `best[vcodec!=h265]/best`.  
You try it out with:  
`yt-dlp -f "best[vcodec!=h265]/best" https://vm.tiktok.com/ZGJbbRe2J/`

I'm about to push a quick fix to use that format filter.  

Thanks for the issue, I had actually ran into this error myself also from time to time. But it was rare enough that I never cared to investigate it.

**Comment by 0x464e** [comment]
Let me know if it works btw. I was pretty eager/confident with closing this. But as long as you're not region locked, I don't see how it couldn't work now.
